server:
  port: 8081

spring:
  application:
    name: spring-ai-pdf-viewer
  ai:
    ollama:
      base-url: http://localhost:1234
      chat:
        options:
          model: qwen3-coder:latest
        timeout: 300s
  webflux:
    multipart:
      max-in-memory-size: 10MB
      max-disk-usage-per-part: 50MB
